HospitalQueue/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from menu import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^queue/', include('hospital_queue_app.urls')),
    url(r'^register/', include('hospital_reception_app.urls')),
    url(r'^patient/', include('hospital_patient_app.urls')),
    url(r'^doctor/', include('hospital_doctor_app.urls')),
    url(r'^/?$', views.menu_index)
]

hospital_queue_app/urls.py
from django.conf.urls import url
from hospital_queue_app import views


app_name = "hospital_queue_app"

urlpatterns = [
    url(r'^index/', views.index, name="index"),
    url(r'^doctors/', views.get_doctors, name="doctors"),
    url(r'^', views.universal_queue, name="all"),
]

hospital_reception_app/urls.py
from django.conf.urls import url
from . import views

app_name = "hospital_reception_app"

urlpatterns = [
    url(r'^login/', views.log_in, name="login"),
    url(r'^logout/', views.log_out, name="logout"),
    url(r'^$', views.index_of_receptionist, name="home"),
    url(r'^search_result/', views.search_patient, name="search_patient"),
    url(r'^patient/signup/$', views.create_patient_request, name="create_patient_request"),
    url(r'^patient/signup/confirm', views.create_patient_response, name="create_patient_response"),
    url(r'^patient/present/toggle', views.change_patient_present_status, name="patient_present_toggle"),
    url(r'^patient/assign/procedure', views.assign_procedure_to_patient, name="assign_procedure_to_patient"),
    url(r'^patient/(?P<pk>\d+)/assign/procedure', views.assign_procedure_to_patient,
        name="assign_procedure_to_patient_with_id"),
    url(r'procedures/$', views.procedures_menu_list, name="procedures"),
    url(r'procedures/detail=(?P<procedure_id>\d+)', views.procedures_detail_queue, name="procedures_detail"),
    url(r'^api/receptionist/(?P<pk>\d+)', views.ReceptionistAPI.as_view()),
]

hospital_queue_app/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser

# Статуси пацієнта
PATIENT_STATUSES = (
    (1, "Звичайний"),
    (2, "VIP"),
    (3, "Нагальний"),
)

# Стани пацієнта
PATIENT_STATES = (
    (1, "відсутній"),
    (2, "відійшов"),
    (3, "в черзі"),
    (4, "очікування"),
    (5, "на процедурах"),
)


# Модель що забезпечує список пацієнтів
class Patient(AbstractBaseUser):
    USERNAME_FIELD = 'email'
    email = models.EmailField(max_length=255, verbose_name="Електронна адреса", unique=True)
    surname = models.CharField(max_length=255, verbose_name="Прізвище")
    name = models.CharField(max_length=255, verbose_name="Ім'я")
    father_name = models.CharField(max_length=255, verbose_name="По-Батькові")
    date_of_birth = models.DateField(verbose_name="Дата народження")
    phone = models.CharField(max_length=20, verbose_name="Номер мобільного")
    patient_status = models.IntegerField(choices=PATIENT_STATUSES, default=1)
    patient_present_state = models.SmallIntegerField(verbose_name="Стан присутністі пацієнта", default=1,
                                                     choices=PATIENT_STATES)
    patient_present_time = models.DateTimeField(verbose_name="Час появи в черзі", auto_now_add=True)
    balance_of_funds = models.FloatField(verbose_name="Баланс коштів", default=0.0)

    class Meta:
        verbose_name_plural = "Пацієнти"
        verbose_name = "пацієнт"

    def __str__(self):
        return self.surname + " " + self.name + " " + self.father_name

    def get_short_name(self):
        return self.surname+" "+self.name

    def get_full_name(self):
        return self.surname + " " + self.name+" "+self.father_name


# Модель що забезпечує список кабінетів
class Cabinet(models.Model):
    name = models.CharField(max_length=100, verbose_name="Назва кабінету")
    number = models.CharField(max_length=15, verbose_name="Номер кабінету")
    floor = models.CharField(max_length=10, verbose_name="Поверх")

    class Meta:
        verbose_name_plural = "Кабінети"
        verbose_name = "кабінет"

    def __str__(self):
        return self.name


# Модель що використовується для визначення професії лікаря
class Profession(models.Model):
    profession_name = models.CharField(max_length=255, verbose_name="Назва професії")
    profession_description = models.TextField(blank=True, verbose_name="Повний опис професії", null=True)

    class Meta:
        verbose_name_plural = "Професії"
        verbose_name = "професія"

    def __str__(self):
        return self.profession_name


# Модель для лікарів
class Doctor(AbstractBaseUser):
    USERNAME_FIELD = 'email'
    surname = models.CharField(max_length=255, verbose_name="Прізвище")
    name = models.CharField(max_length=255, verbose_name="Ім'я")
    father_name = models.CharField(max_length=255, verbose_name="По-Батькові")
    profession = models.ForeignKey(Profession, on_delete=models.SET_NULL, blank=True, null=True)
    cabinet = models.ForeignKey(Cabinet, on_delete=models.SET_NULL, blank=True, null=True)
    email = models.EmailField(max_length=255, verbose_name="Електронна адреса", unique=True)

    class Meta:
        verbose_name_plural = "Лікарі"
        verbose_name = "лікар"

    def __str__(self):
        return self.surname + " " + self.name + " " + self.father_name + " - " + self.profession.profession_name

    def get_short_name(self):
        return self.surname+" "+self.name

    def get_full_name(self):
        return self.surname + " " + self.name+" "+self.father_name


class Procedure(models.Model):
    name = models.CharField(max_length=100, verbose_name="Назва процедури")
    doctors = models.ManyToManyField(Doctor, verbose_name="Лікарі які проводять процедуру")
    incompatible_procedures = models.ManyToManyField('Procedure', verbose_name="Несумісні процедури", blank=True)
    available_to_registrars = models.BooleanField(verbose_name="Дана професія є доступною для реєстраторів",
                                                  default=False)
    cost = models.FloatField(verbose_name="Вартість процедури", default=0.0)

    class Meta:
        verbose_name_plural = "Проседури"
        verbose_name = "процедура"

    def __str__(self):
        return self.name


# Купа всіх черг
class Heap(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE, verbose_name="Пацієнт")
    procedure = models.ForeignKey(Procedure, on_delete=models.SET_NULL, null=True, blank=True, verbose_name="Процедура")
    procedure_count = models.SmallIntegerField(verbose_name="Кількість сеансів", default=1)
    procedure_finished_count = models.SmallIntegerField(verbose_name="Кількість завершених сеансів",
                                                        default=0)
    doctor = models.ForeignKey(
        Doctor,
        on_delete=models.SET_NULL,
        null=True, blank=True,
        verbose_name="Лікар",
        # limit_choices_to={"id": 1}
    )
    creation_time = models.DateTimeField(verbose_name="Час додавання в чергу", auto_now_add=True, blank=True)
    first_seance_time = models.DateTimeField(verbose_name="Час сеансу", auto_now_add=True, blank=True)

    class Meta:
        verbose_name_plural = "Записи"
        verbose_name = "запис"
        unique_together = ('patient', 'procedure',)

    def __str__(self):
        return str(self.patient) + " - " + str(self.procedure)


class HistoryHeap(Heap):
    class Meta:
        verbose_name_plural = "Історія записів"
        verbose_name = "виконаний запис"

hospital_reception_app/models.py
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User


class Receptionist(User):

    def __str__(self):
        return self.first_name+" "+self.last_name+" ( "+self.username+" )"

    class Meta:
        verbose_name = "реєстратор"
        verbose_name_plural = "Peєстратори"

    def get_absolute_url(self):
        return reverse('hospital_reception_app:detail', kwargs={'pk': self.pk})

hospital_reception_app/forms.py
from django import forms
from hospital_queue_app.models import Patient
import datetime


class PatientForm(forms.ModelForm):
    class Meta:
        model = Patient
        fields = [
            'surname',
            'name',
            'father_name',
            'date_of_birth',
            'phone',
            'email',
            'patient_status'
        ]

hospital_reception_app/views.py
from django.db import IntegrityError
from django.shortcuts import render, Http404, redirect, get_object_or_404, HttpResponse
from django.utils.datastructures import MultiValueDictKeyError
from django.contrib.auth import *
from hospital_queue_app.models import Patient, Heap, Procedure
from .models import Receptionist
from .forms import PatientForm

from rest_framework.views import APIView
from rest_framework.response import Response
from .serializers import ReceptionistSerializer

from django.utils import timezone


# api для реєстраторів
class ReceptionistAPI(APIView):
    def get(self, request, pk):
        departments_v = Receptionist.objects.get(pk=pk)
        serializer = ReceptionistSerializer(departments_v, many=False)
        return Response(serializer.data)

    def post(self, request, pk):
        departments_v = Receptionist.objects.get(pk=pk)
        serializer = ReceptionistSerializer(departments_v, many=False)
        return Response(serializer.data)


# Авторизація
def log_in(request):
    try:
        username = request.POST['username']
        password = request.POST['password']
        user = get_object_or_404(Receptionist, username=username, password=password)
        # user = authenticate(request=request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('hospital_reception_app:home')
        else:
            raise Http404
    except Http404:
        return render(request, 'hospital_reception_app/login.html', {"message": "Неправильний логін або пароль"})
    except MultiValueDictKeyError:
        return render(request, 'hospital_reception_app/login.html')


# Не Авторизація
def log_out(request):
    logout(request)
    return redirect('hospital_reception_app:login')


# Виведення основної сторінки для реєстратора
def index_of_receptionist(request):
    return render(request, 'hospital_reception_app/index.html')


# Функція пошуку пацієнтів
def search_patient(request):
    try:
        surname = request.POST['surname']
        name = request.POST['name']
        return render(request, 'hospital_reception_app/patients_result.html',
                      {
                          'patients': Patient.objects.filter(surname=surname, name=name)
                      })
    except MultiValueDictKeyError:
        return HttpResponse("<table></table>Не вдалося знайти жодного пацієнта<script></script>")


# Функція що виводить форму для додавання пацієнта
def create_patient_request(request):
    return render(request, "hospital_reception_app/patients_registration.html",
                  {
                      'form': PatientForm()
                  })


# Функція додавання пацієнта
def create_patient_response(request):
    if request.POST:
        patient = Patient.objects.create(
            surname=request.POST['surname'],
            name=request.POST['name'],
            father_name=request.POST['father_name'],
            date_of_birth=request.POST['date_of_birth'],
            phone=request.POST['phone'],
            email=request.POST['email'],
            patient_status=request.POST['patient_status']
        )
        patient.save()
    return redirect('hospital_reception_app:home')


# Функція зміни статусу присутності пацієнта
def change_patient_present_status(request):
    try:
        if request.POST:
            patient = Patient.objects.get(pk=int(request.POST["patient_pk"]))
            if request.POST["value"] == "true":
                patient.patient_present_state = 3
                patient.patient_present_time = timezone.localtime(timezone.now())
                patient.save()
                return HttpResponse("Статус пацієнта " + str(patient) + " змінено на присутній")
            else:
                patient.patient_present_state = 1
                patient.save()
                return HttpResponse("Статус пацієнта " + str(patient) + " змінено на відсутній")

    except MultiValueDictKeyError:
        return HttpResponse("При спробі змінення статусу пацієнта виникла помилка")


# Додавання пацієнта в чергу
def assign_procedure_to_patient(request, pk=None):
    if pk is not None:
        try:
            patient_id = pk
            return render(
                request,
                'hospital_reception_app/assign_procedure.html',
                {
                    "patient": Patient.objects.get(pk=patient_id),
                    "procedures": Procedure.objects.all().filter(available_to_registrars=True)
                }
            )
        except MultiValueDictKeyError:
            return HttpResponse("При виведенні сторінки виникла помилка")
    else:
        try:
            patient_id = request.POST["patient_id"]
            procedure_id = request.POST["procedure_id"]
            record = Heap.objects.create(patient_id=patient_id, procedure_id=procedure_id)
            record.save()
            return HttpResponse("Пацієнт " + str(Patient.objects.get(pk=patient_id)) +
                                " був доданий в чергу " + str(Procedure.objects.get(pk=procedure_id)))
        except IntegrityError:
            return HttpResponse("Пацієнт " + str(Patient.objects.get(pk=request.POST["patient_id"])) +
                                " вже був доданий в чергу")
        except MultiValueDictKeyError:
            return HttpResponse(
                "При додаванні пацієнта в чергу виникла помилка! "
                "<a href ='{% url \'hospital_reception_app:assign_procedure_to_patient\' "
                "pk=" + request.POST["patient_id"] + "%}'>Спробуйте ще раз</a>"
            )


def procedures_menu_list(request):
    return render(request, "hospital_reception_app/procedures_menu.html", {"procedures": Procedure.objects.all()})


def procedures_detail_queue(request, procedure_id=None):
    return render(request, "hospital_reception_app/procedure_detail_queue.html",
                  {"set": Heap.objects.all().filter(procedure=procedure_id)})

hospital_reception_app/templates/hospital_reception_app/assign_procedure.html
<form action="{% url 'hospital_reception_app:assign_procedure_to_patient' %}" method="post">
    {% csrf_token %}
    <select name="patient_id">
        <option value="{{ patient.pk }}" selected>{{ patient }}</option>
    </select>
    <select name="procedure_id">
        {% for procedure in procedures %}
            <option value="{{ procedure.pk }}">{{ procedure }}</option>
        {% endfor %}
    </select>
    <input type="submit" value="ОК">
</form>
<script>
    $("#assign_procedure>form").submit(function (e) {
        e.preventDefault();
        $.post($(this).attr("action"), $(this).serialize()).done(function (data) {
            $("#assign_procedure").html(data);
        })
    })
</script>

hospital_reception_app/templates/hospital_reception_app/base.html
<!DOCTYPE html>
<html lang="ua">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" href="{% static 'hospital_queue_app/img/medecine.png' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
          integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <script src="{% static 'hospital_reception_app/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'hospital_reception_app/js/jquery-ui.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'hospital_reception_app/css/jquery-ui.min.css' %}">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>
    {% block imports %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-inverse" style="position: fixed; width: 100%">
    <div class="container-fluid">
        <div class="navbar-header">
            <a id="home_link" class="navbar-brand" href="#">Лікарня</a>
        </div>
        <ul class="nav navbar-nav">
            {% block menu_links %}{% endblock %}
        </ul>
        <ul class="nav navbar-nav navbar-right">
            {% if user and user.is_authenticated %}
                <li><a href="#"><span class="glyphicon glyphicon-user"></span>{{ user.username }}</a></li>
                <li><a href="{% url 'hospital_reception_app:logout' %}"><span class="glyphicon glyphicon-log-in"></span>Вихід</a>
                </li>
            {% else %}
                <li><a href="{% url 'hospital_reception_app:login' %}"><span class="glyphicon glyphicon-log-in"></span>Вхід</a>
                </li>
            {% endif %}

        </ul>
    </div>
</nav>

{% if user and user.is_authenticated %}
    {% block content %}{% endblock %}
{% else %}
    Ви не авторизовані
{% endif %}
</body>
</html>

hospital_reception_app/templates/hospital_reception_app/index.html
{% extends "hospital_reception_app/base.html" %}
{% block title %}Пацієнти{% endblock %}
{% block imports %}
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'hospital_reception_app/css/index.css' %}">
{% endblock %}
{% block menu_links %}
    <li><a id="patients_link" href="#patients">Пацієнти</a></li>
    <li><a id="procedures_link" href="#procedures">Процедури</a></li>
{% endblock %}
{% block content %}
    <div id="patients">
        <div id="search_form">
            <form id="search_patient_form" action="{% url 'hospital_reception_app:search_patient' %}"
                  method="post">
                {% csrf_token %}
                <input type="text" placeholder="Прізвище пацієнта" name="surname" class="surname"
                       autocomplete="off"><br>
                <input type="text" placeholder="Ім'я пацієнта" name="name" class="name" autocomplete="off"><br>
                <input type="submit" value="Знайти"><br>
            </form>
        </div>
        <div id="search_result"></div>
        <div id="add_patient" title="Зареєструвати нового пацієнта"></div>
        <div id="assign_procedure" title="Записати в чергу"></div>
        <div id="queue"></div>
    </div>
    <div id="procedures">
        <div id="procedure_selector"></div>
        <div id="queue_display"></div>
    </div>

    <!-- Керування градієнтом -->
    <script>
        function angle(_x, _y) {
            var x = _x - (window.innerWidth / 2);
            var y = _y - (window.innerHeight / 2);
            if (y < 0) {
                return -Math.acos((x * x) / (Math.sqrt(x * x + y * y) * x))
            }
            else if (y > 0) {
                return Math.acos((x * x) / (Math.sqrt(x * x + y * y) * x))
            }

        }
        $("#patients").mousemove(function () {
            $(this).css('background', 'linear-gradient(' + (Math.PI / 2 + angle(event.clientX, event.clientY)) + 'rad, #4dff4d, #3399FF)');
        });
        $("#procedures").mousemove(function () {
            $(this).css('background', 'linear-gradient(' + (Math.PI / 2 + angle(event.clientX, event.clientY)) + 'rad, #4dff4d, #3399FF)');
        });
    </script>

    <!-- Керування посиланнями в меню -->
    <script>
        $("#home_link").click(function (e) {
            e.preventDefault();
        });
        $("#patients_link").click(function (e) {
            e.preventDefault();
            $("#patients").css('z-index', '-1');
            $("#procedures").css('z-index', '-2');
        });
        $("#procedures_link").click(function (e) {
            e.preventDefault();
            $("#patients").css('z-index', '-2');
            $("#procedures").css('z-index', '-1');
        });
    </script>

    <!-- Керування блоком пацієнти -->
    <script>
        $('#add_patient').dialog({
            modal: true,
            autoOpen: false
        });
        $('#assign_procedure').dialog({
            modal: true,
            autoOpen: false
        });
        $('#search_patient_form').submit(function (event) {
            event.preventDefault();
            $.ajax({
                type: 'POST',
                url: '{% url 'hospital_reception_app:search_patient' %}',
                data: {
                    'surname': $('.surname').val(),
                    'name': $('.name').val(),
                    'csrfmiddlewaretoken': $("input[name=csrfmiddlewaretoken]").val()
                },
                success: function (data) {
                    $("#search_result").html(data)
                },
                dataType: 'html'
            });
            $("input:text").val("");
        });
        document.addEventListener("DOMContentLoaded", function (event) {
            setInterval(function () {
                $.get({% url 'hospital_queue_app:all' %}, function (data) {
                    $("#queue").html(data);
                });
            }, 1000);
        });
    </script>

    <!-- Керування блоком процедури -->
    <script>
        $.get("{% url 'hospital_reception_app:procedures' %}", function (data) {
            $("#procedure_selector").html(data);
        });
    </script>
{% endblock %}

hospital_reception_app/templates/hospital_reception_app/patients_registration.html
<form action="{% url "hospital_reception_app:create_patient_response" %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Зареєструвати">
</form>

hospital_reception_app/templates/hospital_reception_app/patients_result.html
{% if patients %}
    <table class="table table-striped">
        <thead>
        <tr>
            <th>Ім'я</th>
            <th>Дата народження</th>
            <th>Статус</th>
            <th>Присутність</th>
            <th>Баланс коштів</th>
            <th>Направлення</th>
        </tr>
        </thead>
        <tbody>
        {% csrf_token %}
        {% for patient in patients %}
            <tr>
                <td>{{ patient }} </td>
                <td>{{ patient.date_of_birth }}</td>
                <td>{{ patient.get_patient_status_display }}</td>
                <td><label class="switch"><input type="checkbox" value="{{ patient.pk }}"
                                                 {% if patient.patient_present_state is not 1 %}checked{% endif %}>
                    <span
                            class="slider round"></span> </label></td>
                <td>
                    <p {% if patient.balance_of_funds < 0 %}style="color: red" {% endif %}>{{ patient.balance_of_funds }}</p>
                </td>
                <td><a class="put_patient_in_queue"
                       href="{% url 'hospital_reception_app:assign_procedure_to_patient_with_id' pk=patient.pk %}">Додати</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <style>
        .switch {
            position: relative;
            display: inline-block;
            width: 35px;
            height: 21px;
        }

        .switch input {
            display: none;
        }

        .slider {
            position: absolute;
            cursor: pointer;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            background-color: #ccc;
            -webkit-transition: .4s;
            transition: .4s;
        }

        .slider:before {
            position: absolute;
            content: "";
            height: 15px;
            width: 15px;
            left: 4px;
            bottom: 3px;
            background-color: white;
            -webkit-transition: .4s;
            transition: .4s;
        }

        input:checked + .slider {
            background-color: #2196F3;
        }

        input:focus + .slider {
            box-shadow: 0 0 1px #2196F3;
        }

        input:checked + .slider:before {
            -webkit-transform: translateX(26px);
            -ms-transform: translateX(26px);
            transform: translateX(13px);
        }

        /* Rounded sliders */
        .slider.round {
            border-radius: 34px;
        }

        .slider.round:before {
            border-radius: 50%;
        }
    </style>
    <script>
        $("input:checkbox").click(function () {
            var id = $(this)[0].value;
            var val = $(this)[0].checked;
            $.ajax({
                type: 'POST',
                url: '{% url 'hospital_reception_app:patient_present_toggle' %}',
                data: {
                    'patient_pk': id,
                    'value': val,
                    'csrfmiddlewaretoken': $("input[name=csrfmiddlewaretoken]").val()
                },
                success: function (data, textStatus, jqXHR) {
                    console.log(data);
                },
                dataType: 'html'
            });
        });
        $(".put_patient_in_queue").click(function (e) {
            e.preventDefault();
            $.get($(this).attr("href"), function (data) {
                $('#assign_procedure').html(data).dialog("open");
            });
        });
    </script>
{% else %}
    Не знайдено жодного пацієнта <br>
    <a id="add_patient_link" href="{% url "hospital_reception_app:create_patient_request" %}">Новий пацієнт</a>
    <script>
        $("#add_patient_link").click(function (e) {
            e.preventDefault();
            $.get($(this).attr("href"), function (data) {
                $('#add_patient').html(data).dialog("open");
            });
        });
    </script>
{% endif %}

hospital_reception_app/templates/hospital_reception_app/procedure_detail_queue.html
<div id="patients_count">Кількість пацієнтів яким призначена дана процедура - {{ set|length }}</div>
{% if set|length > 0 %}
    <script>
    $(".cost").each(function () {
        $(this).html($(this).children(".a").html()*parseFloat($(this).children(".b").html())).removeClass("cost")
    });
    </script>
    <table>
        <thead>
        <tr>
            <th>Пацієнт</th>
            <th>Кількість сеансів</th>
            <th style="text-align: center">Дата найближчого сеансу</th>
            <th style="text-align: center">Вартість пройдених процедур</th>
            <th style="text-align: center">Вартість всіх процедур</th>
        </tr>
        </thead>
        <tbody>
        {% for item in set %}
            <tr>
                <td>{{ item.patient }}</td>
                <td>{{ item.procedure_finished_count }}/{{ item.procedure_count }}</td>
                <td style="text-align: center">{{ item.first_seance_time }}</td>
                <td style="text-align: center" class="cost"><div class="a">{{ item.procedure_finished_count }}</div><div class="b">{{ item.procedure.cost }}</div></td>
                <td style="text-align: center" class="cost"><div class="a">{{ item.procedure_count }}</div><div class="b">{{ item.procedure.cost }}</div></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endif %}

hospital_reception_app/templates/hospital_reception_app/procedures_menu.html
<ul>
    {% for procedure in procedures %}
        <a class="procedure_link" href="{% url 'hospital_reception_app:procedures_detail' procedure_id=procedure.pk %}">
            <li>
                {{ procedure.name }}
            </li>
        </a>
    {% endfor %}
</ul>
<script>
    $(".procedure_link").click(function (e) {
        e.preventDefault();
        $.get($(this).attr("href"), function (data) {
            $("#queue_display").html(data);
        });
        $("#procedure_selector>ul>a>li")
            .css({"border": "none", "background": "#ffffff80"})
            .hover(function () {
                $(this).css("background", "#fffffff0");
            }, function () {
                $(this).css("background", "#ffffff80");
            });
        $(this).children("li").css({"border": "2px solid black", "background": "#fffffff0"})
            .hover(function () {
                $(this).css("background", "#fffffff0");
            }, function () {
                $(this).css("background", "#fffffff0");
            });
    });
</script>